### ISSUE TITLE
Zone, Station objectives not using mover modulo positions

### ISSUE THREAD

**Issue by giantlol** [Beckhoff-USA-Community/XTS_Base#43]
In #37, in Zone.CurrentMoverList, this:

`internalTrackedMovers[i]^.AxisReference.NcToPlc.ModuloActPos`

was changed to this:

`internalTrackedMovers[i]^.TrackInfo.TrackPosition`

but the TrackPosition returned from MC_ReadTrackPositions is not a modulo position (at least not in version 3.2.33.0 of TF5410), so the mover registration is not working as I'd expect.  There might be a similar issue in Station.MoverInPosition (the "unwrap" logic does not look like it's equivalent to using the modulo position or doing a modabs), but I'm not using that yet so I haven't tested it.

![image](https://github.com/Beckhoff-USA-Community/XTS_Base/assets/64655732/d753ac9b-533c-49a3-9688-4392906c38be)

**Comment by netbymatt** [comment]
We've seen this and have identified a few solutions to the issue. I'll pick one of them and post it in a separate branch for you to try out.

**Comment by netbymatt** [comment]
Can you try e284a61c21b903292c11a3ea40eb9779a08c80dd in [position-modulo](/Beckhoff-USA-Community/XTS_Base/tree/position-modulo)?

The problem comes from defaulting the track number to zero which is a special case that uses an absolute reference and does not use modulus. The changes in the code set all the movers to track 1 and default all zones, stations and position triggers to track 1 as well.

This is a screenshot taken after the changes were made and includes the same information in your previous screenshot. You can see the track position is now using modulus.

![image](https://github.com/Beckhoff-USA-Community/XTS_Base/assets/51417385/c40437e1-7804-4cf8-820e-5826c8cd0c59)
